import{a as f,S as m,i as a}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y="49622703-1639e63074f827bd1b79f059d",g="https://pixabay.com/api/";async function p(s){try{return(await f.get(g,{params:{key:y,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(r){throw console.error("Error fetching images:",r),r}}const c=document.querySelector(".gallery");let h=new m(".gallery a");function L(s){const r=s.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:n,comments:u,downloads:d})=>`
      <a href="${i}" class="gallery-item">
        <img src="${o}" alt="${e}" loading="lazy" />
        <div class="info">
          <p>👍 Likes: ${t}</p>
          <p>👁️ Views: ${n}</p>
          <p>💬 Comments: ${u}</p>
          <p>⬇️ Downloads: ${d}</p>
        </div>
      </a>
    `).join("");c.innerHTML=r,h.refresh()}function b(){c.innerHTML=""}function S(){document.querySelector(".loader").classList.add("visible")}function w(){document.querySelector(".loader").classList.remove("visible")}const q=document.querySelector(".form"),v=document.querySelector('input[name="search-text"]'),l=document.querySelector(".loading-message");function P(){l.style.display="block"}function $(){l.style.display="none"}q.addEventListener("submit",async s=>{s.preventDefault();const r=v.value.trim();if(!r){a.warning({title:"Warning",message:"Search field cannot be empty!"});return}b(),S(),P();try{const o=await p(r);o.hits.length===0?a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):L(o.hits)}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{w(),$()}});
//# sourceMappingURL=index.js.map
