import{a as f,S as p,i}from"./assets/vendor-BfjKTZs6.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const m="49622703-1639e63074f827bd1b79f059d",y="https://pixabay.com/api/";async function g(s){try{return(await f.get(y,{params:{key:m,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(r){throw console.error("Error fetching images:",r),r}}const l=document.querySelector(".gallery");let h=new p(".gallery a");function L(s){const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:n,comments:u,downloads:d})=>`
      <a href="${a}" class="gallery-item">
        <img src="${o}" alt="${e}" loading="lazy" />
        <div class="info">
          <p> Likes: <span class="info-value">${t}</span></p>
          <p> Views: <span class="info-value">${n}</span></p>
          <p> Comments: <span class="info-value">${u}</span></p>
          <p> Downloads: <span class="info-value">${d}</span></p>
        </div>
      </a>
    `).join("");l.innerHTML=r,h.refresh()}function v(){l.innerHTML=""}function b(){document.querySelector(".loader").classList.add("visible")}function S(){document.querySelector(".loader").classList.remove("visible")}const w=document.querySelector(".form"),q=document.querySelector('input[name="search-text"]'),c=document.querySelector(".loading-message");function P(){c.style.display="block"}function $(){c.style.display="none"}w.addEventListener("submit",async s=>{s.preventDefault();const r=q.value.trim();if(!r){i.warning({title:"Warning",message:"Search field cannot be empty!"});return}v(),b(),P();try{const o=await g(r);o.hits.length===0?i.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"}):L(o.hits)}catch{i.error({title:"Error",message:"Something went wrong. Please try again later!"})}finally{S(),$()}});
//# sourceMappingURL=index.js.map
